spring:
  application:
    name: kafka-consumer
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
      - localhost:9095
      - localhost:9096
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      client-id: kafka-consumer
      group-id: kafka-consumer
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      concurrency: 10
      properties:
        max.poll.interval.ms: 300000
        session.timeout.ms: 10000
        max.poll.records: 500
        request.timeout.ms: 30000
        group.initial.rebalance.delay.ms: 5000
        fetch.max.wait.ms: 1000
    properties: # for KafkaAvroDeserializer
      schema.registry.url: http://localhost:8081
      specific.avro.reader: false
  profiles:
    include: consumers

database:
  url: jdbc:mariadb://localhost/account?maxPoolSize=20
  username: account_user
  password: pump3rn1ck3l

---

spring.profiles: docker

spring:
  kafka:
    bootstrap-servers:
      - broker1:19092
      - broker2:19093
      - broker3:19094
      - broker4:19095
      - broker5:19096
    properties:
      # for KafkaAvroDeserializer
      schema.registry.url: http://schema-registry:8081

database:
  url: jdbc:mariadb://mariadb/account?maxPoolSize=20