spring:
  application:
    name: spring-kafka-consumer
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
      - localhost:9095
      - localhost:9096
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      client-id: spring-kafka-client-9
      group-id: person-consumer-spring
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      concurrency: 10
      properties:
        max.poll.interval.ms: 20000
        session.timeout.ms: 20000
        max.poll.records: 500
        request.timeout.ms: 25000
        group.initial.rebalance.delay.ms: 5000
    properties: # for KafkaAvroDeserializer
      schema.registry.url: http://localhost:8081
      specific.avro.reader: false
    streams:
      application-id: spring-kafka-stream
  profiles:
    active: development
    include: consumers