streams:
  account:
    enabled: true
    type: generic-aggregate
    inputTopic: person,address,phone
    outputTopic: account
    keySchema: schemas/account-key.avsc,schemas/address-key.avsc,schemas/phone-key.avsc
    valueSchema: schemas/account-value.avsc,schemas/address-value.avsc,schemas/phone-value.avsc