spring:
  application:
    name: kafka-producer
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
      - localhost:9095
      - localhost:9096
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties: # for KafkaAvroDeserializer
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
  profiles:
    include: producers

schedule.send.rate.ms: 250
task.pool.size: 20

---

spring.profiles: docker

spring:
  kafka:
    bootstrap-servers:
      - broker1:19092
      - broker2:19093
      - broker3:19094
      - broker4:19095
      - broker5:19096
    properties:
      # for KafkaAvroDeserializer
      schema.registry.url: http://schema-registry:8081