producers:
  phone:
    enabled: false
    type: generic
    outputTopic: phone
    keySchema: schemas/phone-key.avsc
    valueSchema: schemas/phone-value.avsc
    batchSize: 100
  thing-0:
    enabled: true
    type: generic
    outputTopic: thing-0
    keySchema: schemas/thing-key.avsc
    valueSchema: schemas/thing-value.avsc
    batchSize: 100
  thing-1:
    enabled: true
    type: generic
    outputTopic: thing-1
    keySchema: schemas/thing-key.avsc
    valueSchema: schemas/thing-value.avsc
    batchSize: 100
  thing-2:
    enabled: true
    type: generic
    outputTopic: thing-2
    keySchema: schemas/thing-key.avsc
    valueSchema: schemas/thing-value.avsc
    batchSize: 100
  thing-3:
    enabled: true
    type: generic
    outputTopic: thing-3
    keySchema: schemas/thing-key.avsc
    valueSchema: schemas/thing-value.avsc
    batchSize: 100
  thing-4:
    enabled: true
    type: generic
    outputTopic: thing-4
    keySchema: schemas/thing-key.avsc
    valueSchema: schemas/thing-value.avsc
    batchSize: 100
#  person:
#    enabled: true
#    type: specific
#    topic: person
#    generatorClass: com.opi.kafka.producer.specific.PersonGenerator
#  address:
#    enabled: false
#    type: generic
#    topic: address
#    keySchema: schemas/address-key.avsc
#    valueSchema: schemas/address-value.avsc