spring:
  application:
    name: spring-kafka-producer
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
      - localhost:9095
      - localhost:9096
    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties: # for KafkaAvroDeserializer
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    streams:
      application-id: spring-kafka-stream
  profiles:
    active: development

producers:
  person.enabled: true
  generic:
    enabled: false
    keySchema: schemas/person-key.avsc
    valueSchema: schemas/person-value.avsc

topics:
  people: person